###   Various configurable bits  ###
# Build a pack for the current OS (one of "win", "osx", "linux")
os: win
# "32" or "64" as a string
desired_bits: "32"
# Packname, will format with first line of base/changelog.txt
packname: "PeridexisErrant's Starter Pack {}"
# Which graphics pack should be installed by default
default_graphics: Phoebus
# Forum post, see dist.py and save with whitespace!
forum_post: |
    The Starter Pack has updated to {PACK_VERSION}!
    As usual, [url={LINK}]you can get it here.[/url]
    
    {CHANGELOG}
    
    SHA256:  {CHECKSUM}
    
    [i]If you want to say thanks, check out [url=https://www.patreon.com/bay12games]Toady's Patreon[/url], or even [url=https://www.patreon.com/PeridexisErrant]mine![/url][/i]  ;D
# Use latest DF version, or override to match DFHack?
force_dfhack_compatible: True
# Are alpha releases OK?  (GitHub only; False for stable packs)
allow_prerelease_components: False
