###   Various configurable bits.  Also check command-line options with `main.py -h`  ###
# Packname, will format with first line of base/changelog.txt
packname: "PeridexisErrant's Starter Pack {}"
# Which graphics pack should be installed by default
default_graphics: Phoebus
# Forum post, see dist.py and save with whitespace!
forum_post: |
    The Starter Pack has updated to {PACK_VERSION}!
    As usual, [url={LINK}]you can get it here.[/url]
    _
    {CHANGELOG}
    _
    SHA256:  {CHECKSUM}
    _
    [i]If you want to say thanks, check out [url=https://www.patreon.com/bay12games]Toady's Patreon[/url], or even [url=https://www.patreon.com/PeridexisErrant]mine![/url][/i]  ;D
unstable_forum_post: |
    [size=18pt]The Starter Pack has updated to {PACK_VERSION}![/size]
    [url={LINK}]You can get alpha versions of the starter pack here.[/url]
    _
    {CHANGELOG}
    _
    SHA256:  {CHECKSUM}
    _
    [i]If you want to say thanks, check out [url=https://www.patreon.com/bay12games]Toady's Patreon[/url], or even [url=https://www.patreon.com/PeridexisErrant]mine![/url][/i]  ;D
# point PyLNP at the right hosting link for updates
dffdID: "7622"
unstable_dffdID: "13201"
